// GENERATED by reference/python/export_registers.py. Do not edit by hand.
// Radar SDK 3.6.4+4b4a6245, sensor BGT60TR13C, exported 2026-10-05.
// BGT60TR13C register list for the SensDSv2 configuration, as saved by the
// SDK's save_register_file() (NAME 0xADDRESS 0xVALUE per line).

import { parseRegisterFile } from './registers.js';

export const EXPORT_INFO = {
  "sdk_version": "3.6.4+4b4a6245",
  "sensor": "BGT60TR13C",
  "board_uuid": "00323353-4e39-4b4a-3138-303331303331",
  "firmware": {
    "description": "Radar Baseboard MCU7 (MCU B)",
    "version_major": "2",
    "version_minor": "9",
    "version_build": "0",
    "extended_version": "2.9.0"
  },
  "date": "2026-10-05",
  "config": {
    "frame_repetition_time_s": 0.1,
    "chirp_repetition_time_s": 0.0002,
    "num_chirps": 128,
    "tdm_mimo": false,
    "start_frequency_Hz": 58000000000.0,
    "end_frequency_Hz": 63500000000.0,
    "sample_rate_Hz": 2000000.0,
    "num_samples": 256,
    "rx_mask": 7,
    "tx_mask": 1,
    "tx_power_level": 31,
    "lp_cutoff_Hz": 500000,
    "hp_cutoff_Hz": 80000,
    "if_gain_dB": 33
  },
  "frames": {
    "count": 20,
    "dropped": 0,
    "shape": [
      20,
      3,
      128,
      256
    ],
    "mean_per_antenna": [
      -0.20564548671245575,
      -0.008651403710246086,
      0.016724739223718643
    ],
    "std_per_antenna": [
      0.14792393147945404,
      0.11980128288269043,
      0.04095602035522461
    ]
  }
};

export const REGISTER_FILE = `MAIN 0x0000 0x001e8270
ADC0 0x0001 0x000a0210
PACR1 0x0004 0x00e967fd
PACR2 0x0005 0x000805b4
SFCTL 0x0006 0x001027ff
SADC_CTRL 0x0007 0x00010f00
CSP_I_0 0x0008 0x00000000
CSP_I_1 0x0009 0x00000000
CSP_I_2 0x000a 0x00000000
CSCI 0x000b 0x00000be0
CSP_D_0 0x000c 0x00000000
CSP_D_1 0x000d 0x00000000
CSP_D_2 0x000e 0x00000000
CSCDS 0x000f 0x00000b60
CS1_U_0 0x0010 0x0013fc51
CS1_U_1 0x0011 0x007ff41f
CS1_U_2 0x0012 0x00703def
CS1 0x0016 0x00000490
CS2 0x001d 0x00000480
CS3 0x0024 0x00000480
CS4 0x002b 0x00000480
CCR0 0x002c 0x0011be0e
CCR1 0x002d 0x00659c0a
CCR2 0x002e 0x0007f000
CCR3 0x002f 0x00787e1e
PLL1_0 0x0030 0x00a808ae
PLL1_1 0x0031 0x0000035b
PLL1_2 0x0032 0x00000532
PLL1_3 0x0033 0x00000100
PLL1_4 0x0034 0x00000000
PLL1_5 0x0035 0x00000000
PLL1_6 0x0036 0x00000000
PLL1_7 0x0037 0x0003d310
PLL2_7 0x003f 0x00000100
PLL3_7 0x0047 0x00000100
PLL4_7 0x004f 0x00000100
RFT1 0x0056 0x00000000
SDFT0 0x005b 0x00000000
`;

export const REGISTERS = parseRegisterFile(REGISTER_FILE);
