"""
One-time export of the BGT60TR13C register list for the SensDSv2 configuration.
Developer tool, run once; the web app never runs Python.

What it does, in order:
  1. Opens the radar with the Infineon Radar SDK 3.6.4 (DeviceFmcw), the same
     SDK and calls SensDSv2 uses when you press Connect Radar.
  2. Applies the SensDSv2 configuration (values copied from SensDSv2
     core/radar.py build_config) and saves the register list the SDK computes.
  3. Optionally captures a few frames of a still scene with the SDK, as the
     reference the web version is checked against (--frames N, default 20;
     --frames 0 to skip).
  4. Closes the radar (the SDK stops acquisition and resets the chip).

Writes into this project:
  src/avian/registers_tr13c.js              register list as data, used by the web app
  tests/fixtures/radar/registers_sdk364.txt the SDK's own export, unchanged
  tests/fixtures/radar/python_frames.npy    captured frames (n, 3, 128, 256) float32
  tests/fixtures/radar/export_info.json     SDK version, sensor, board, date

Run (see docs/procedures/export_registers.md):
    python reference/python/export_registers.py
"""
import argparse
import datetime
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "tests" / "fixtures" / "radar"
JS_OUT = ROOT / "src" / "avian" / "registers_tr13c.js"

# SensDSv2 core/radar.py build_config(), copied as literals.
SENSDS_CONFIG = dict(
    frame_repetition_time_s=0.10,
    chirp_repetition_time_s=0.0002,
    num_chirps=128,
    tdm_mimo=False,
    start_frequency_Hz=58.0e9,
    end_frequency_Hz=63.5e9,
    sample_rate_Hz=2e6,
    num_samples=256,
    rx_mask=7,
    tx_mask=1,
    tx_power_level=31,
    lp_cutoff_Hz=500000,
    hp_cutoff_Hz=80000,
    if_gain_dB=33,
)


def build_config():
    from ifxradarsdk.fmcw.types import FmcwSimpleSequenceConfig
    c = SENSDS_CONFIG
    cfg = FmcwSimpleSequenceConfig()
    cfg.frame_repetition_time_s = c["frame_repetition_time_s"]
    cfg.chirp_repetition_time_s = c["chirp_repetition_time_s"]
    cfg.num_chirps = c["num_chirps"]
    cfg.tdm_mimo = c["tdm_mimo"]
    cfg.chirp.start_frequency_Hz = c["start_frequency_Hz"]
    cfg.chirp.end_frequency_Hz = c["end_frequency_Hz"]
    cfg.chirp.sample_rate_Hz = c["sample_rate_Hz"]
    cfg.chirp.num_samples = c["num_samples"]
    cfg.chirp.rx_mask = c["rx_mask"]
    cfg.chirp.tx_mask = c["tx_mask"]
    cfg.chirp.tx_power_level = c["tx_power_level"]
    cfg.chirp.lp_cutoff_Hz = c["lp_cutoff_Hz"]
    cfg.chirp.hp_cutoff_Hz = c["hp_cutoff_Hz"]
    cfg.chirp.if_gain_dB = c["if_gain_dB"]
    return cfg


def write_js(register_text, info):
    lines = [l for l in register_text.splitlines() if l.strip()]
    body = "\n".join(lines)
    JS_OUT.write_text(
        "// GENERATED by reference/python/export_registers.py. Do not edit by hand.\n"
        f"// Radar SDK {info['sdk_version']}, sensor {info['sensor']}, exported {info['date']}.\n"
        "// BGT60TR13C register list for the SensDSv2 configuration, as saved by the\n"
        "// SDK's save_register_file() (NAME 0xADDRESS 0xVALUE per line).\n\n"
        "import { parseRegisterFile } from './registers.js';\n\n"
        f"export const EXPORT_INFO = {json.dumps(info, indent=2)};\n\n"
        f"export const REGISTER_FILE = `{body}\n`;\n\n"
        "export const REGISTERS = parseRegisterFile(REGISTER_FILE);\n"
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--frames", type=int, default=20, help="frames to capture as reference (0 to skip)")
    args = ap.parse_args()

    try:
        import ifxradarsdk
        from ifxradarsdk.fmcw import DeviceFmcw
    except ImportError:
        sys.exit("ifxradarsdk is not installed. Follow docs/procedures/export_registers.md, step 1.")

    sdk_version = ifxradarsdk.get_version_full() if hasattr(ifxradarsdk, "get_version_full") else "unknown"
    if not sdk_version.startswith("3.6.4"):
        print(f"WARNING: SDK {sdk_version}; SensDSv2 uses 3.6.4.")

    FIXTURES.mkdir(parents=True, exist_ok=True)
    reg_path = FIXTURES / "registers_sdk364.txt"

    with DeviceFmcw() as device:
        st = device.get_sensor_type()
        sensor = getattr(st, "name", str(st))   # str() of an IntEnum is just the number on Python 3.11+
        print(f"SDK {sdk_version}, sensor {sensor}, board {device.get_board_uuid()}")
        if "BGT60TR13C" not in sensor:
            sys.exit(f"Expected a BGT60TR13C, found {sensor}. Nothing exported.")

        sequence = device.create_simple_sequence(build_config())
        device.set_acquisition_sequence(sequence)
        device.save_register_file(str(reg_path))
        print(f"Saved {reg_path.relative_to(ROOT)}")

        info = {
            "sdk_version": sdk_version,
            "sensor": sensor,
            "board_uuid": device.get_board_uuid(),
            "firmware": {k: str(v) for k, v in device.get_firmware_information().items()},
            "date": datetime.date.today().isoformat(),
            "config": SENSDS_CONFIG,
        }

        if args.frames > 0:
            import numpy as np
            print(f"Capturing {args.frames} frames. Keep the scene still...")
            frames, dropped = [], 0
            while len(frames) < args.frames:
                try:
                    frames.append(np.array(device.get_next_frame()[0], dtype=np.float32))
                except Exception as e:                          # SensDSv2 treats drops as transient
                    if "IFX_ERROR_FRAME_ACQUISITION_FAILED" in str(e):
                        dropped += 1
                        continue
                    raise
            cube = np.stack(frames)
            np.save(FIXTURES / "python_frames.npy", cube)
            info["frames"] = {"count": len(frames), "dropped": dropped, "shape": list(cube.shape),
                              "mean_per_antenna": cube.mean(axis=(0, 2, 3)).tolist(),
                              "std_per_antenna": cube.std(axis=(0, 2, 3)).tolist()}
            print(f"Saved tests/fixtures/radar/python_frames.npy {cube.shape}, {dropped} dropped")

    (FIXTURES / "export_info.json").write_text(json.dumps(info, indent=2))
    write_js(reg_path.read_text(), info)
    print(f"Wrote {JS_OUT.relative_to(ROOT)}")
    print("Done. The radar has been closed.")


if __name__ == "__main__":
    main()
